version: '3.8'

services:
  api:
    container_name: vybes-employees-api
    build: .
    command: sh -c "yarn && yarn start:dev"
    ports:
      - '${PORT}:${PORT}'
    volumes:
      - ./:/app
    env_file:
      - .env
  postgres:
    container_name: vybes-employees-postgres
    image: postgres
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
    ports:
      - '5437:5432'
    volumes:
      - ./postgres.conf:/etc/postgresql/postgresql.conf
      - vybes-employees-postgres:/var/lib/postgresql/data
    env_file:
      - .db.env

volumes:
  vybes-employees-postgres:
